# Generated by Django 5.0.1 on 2024-01-31 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0005_alldata_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionchoice',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_choices', to='jonomotApp.alldata'),
        ),
    ]
