# Generated by Django 5.0.1 on 2024-02-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0006_alter_optionchoice_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reaction_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
