# Generated by Django 5.0.1 on 2024-02-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0007_customuser_comment_points_customuser_reaction_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_user',
            field=models.BooleanField(default=False),
        ),
    ]
