# Generated by Django 5.0.1 on 2024-02-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0008_customuser_premium_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='comment_points',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reaction_points',
        ),
    ]
