# Generated by Django 5.0.1 on 2024-02-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0009_rename_comment_points_customuser_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='is_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alldata',
            name='is_poll',
            field=models.BooleanField(default=False),
        ),
    ]
