# Generated by Django 5.0.1 on 2024-03-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0013_alter_customuser_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='post_type',
            field=models.CharField(blank=True, choices=[('image/video', 'image/video'), ('text', 'text'), ('image2', 'image2')], max_length=15, null=True),
        ),
    ]
