# Generated by Django 5.0.1 on 2024-03-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0014_alter_alldata_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='Share_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
