# Generated by Django 4.2.11 on 2024-08-21 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0015_alldata_share_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='notice',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
