# Generated by Django 4.2.11 on 2024-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonomotApp', '0016_alter_alldata_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
